import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const roles = [
['program-manager','Head','User/project owner','User request, board, head reviews, quality evidence','Approved scope, assignments, risks, deadline log, closure decision','Never invent deadlines, percentages, or release readiness','Route intake to appropriate head; send completion packet to quality head; close only after gates'],
['work-intake','Specialist','Program manager','User request, issue, feedback provenance','Task card with acceptance criteria, sensitivity, owner proposal and dependencies','Do not convert wishes into live features or promise a date','Send scoped card to program manager'],
['progress-tracker','Specialist','Program manager','Board, commits, test reports, deployment evidence','Website/app progress note separating code, tested build, and live deployment','Do not claim public availability from source or a screenshot','Send status and stale-evidence flags to program manager'],
['app-coordinator','Specialist','Program manager','Task needs, available tool inventory, data class','Suggested creative/AI app, verified access status, privacy/licensing/accessibility conditions','Never claim integration from an exposed tool or send student data without approval','Send tool recommendation to task head and program manager'],
['learning-product-head','Head','Program manager','Research, feedback, curriculum outputs, product scope','Reviewed learning requirements and evidence gaps','Do not generalize a small survey or call learning estimates grades','Review all branch specialists, then hand requirements to design and engineering heads'],
['student-feedback','Specialist','Learning/product head','Consent appropriate actual feedback, dated source and cohort context','De-identified findings with provenance, sample limits, and unanswered questions','Never fabricate quotes, participants, responses or raw student identifiers','Send evidence ledger and findings to learning/product head'],
['learning-research','Specialist','Learning/product head','Real feedback, usage evidence, study flow and learning goals','Research questions, method, observed findings, limitations, proposed validation','Do not treat product assumptions or synthetic demos as research findings','Send method and findings to learning/product head'],
['content-curriculum','Specialist','Learning/product head','Teacher approved syllabus, licensed sources, quiz explanations','Attributed content plan, review checklist, accuracy and permission evidence','No unverified course authority, copyrighted uploads, or generated content labeled verified','Send content for teacher/domain review and learning/product head approval'],
['design-head','Head','Program manager','Reviewed requirements, design specialist outputs','Reviewed cohesive flow, copy, visual and interaction packet','Do not mark proposed screens implemented','Review each design specialist and send spec to engineering head'],
['ux-writing','Specialist','Design head','Student journeys, error/offline states, age and language needs','Plain language labels, messages, empty/error/offline copy','Avoid shame, dark patterns, unsupported promises and sensitive details','Send copy and rationale to design head and accessibility specialist'],
['ux-design','Specialist','Design head','Current screens, personas backed by evidence, task flows','Wireflows for solo study, optional competition, Studio and admin as relevant','Distinguish current behavior from proposed changes','Send flow and edge cases to design head'],
['visual-design','Specialist','Design head','Tokens, existing CSS/assets, approved brand direction','Visual specifications and asset provenance','Do not reuse unlicensed imagery or imply UI is shipped','Send visual specs to design head and accessibility specialist'],
['interaction-design','Specialist','Design head','Current client interactions, motion settings, touch/keyboard requirements','State diagrams, focus/feedback/motion behavior','Do not rely on animation alone; respect reduced motion','Send interactions to design head, engineering and QA'],
['accessibility','Specialist','Design head','Flows, copy, UI build, assistive technology evidence','Accessibility findings and test matrix with severity and reproduction','Automated scans alone do not establish conformance','Send findings to design head, engineering and QA'],
['engineering-head','Head','Program manager','Approved specs, code changes, security findings','Reviewed implementation plan and change packet','Do not bypass security review or call source a deployed release','Review engineering/security specialists; send build to quality head'],
['engineering','Specialist','Engineering head','Approved task, Java/JS/Capacitor code, architecture docs','Implementation, changed files, tests, rollback notes','Use synthetic test data; no secrets or student data in repo','Send diff and evidence to engineering head, security specialist and code reviewer'],
['security-privacy','Specialist','Engineering head','Data flows, auth/roles, uploads, AI, rooms, rewards and admin changes','Threat/privacy review with concrete findings and mitigations','Do not expose private data or claim compliance certification','Send findings to engineering head and quality head'],
['quality-head','Head','Program manager','Change packet and acceptance criteria','Independent gate decision with linked evidence and open findings','Cannot self-approve a producing branch or infer quality percentage','Review QA, independent verification and code review; return failures to owner'],
['qa-testing','Specialist','Quality head','Acceptance criteria, changed build, test plan','Reproducible results for happy, empty, error, offline, mobile and role cases as relevant','No pass without executing and recording environment/result','Send results and defects to quality head and owning head'],
['independent-verification','Specialist','Quality head','Claimed result, source evidence, running behavior','Independent check of requirements, feature status and evidence freshness','Do not rely only on author statements or old reports','Send discrepancies to quality head and program manager'],
['code-review','Specialist','Quality head','Diff, architecture, tests, security notes','Review findings on correctness, maintainability, privacy and regression risk','Do not approve own code or substitute tests for review','Send findings to quality head and engineering head']
];

mkdirSync(new URL('./roles/', import.meta.url), {recursive:true});
for (const [slug,level,reports,inputs,outputs,limits,handoff] of roles) {
 const title=slug.split('-').map(s=>s[0].toUpperCase()+s.slice(1)).join(' ');
 const body=`# ${title}\n\n**Position:** ${level}. **Reports to:** ${reports}.\n\n## Responsibility\n\n${outputs.split(',')[0]}. Work only on Study Arena tasks assigned through the [task board](../TASK_BOARD.md), using the [feature map](../FEATURE_MAP.md) and [workflow](../WORKFLOW.md).\n\n## Inputs\n\n${inputs}. Check source, date, consent and whether each feature is current, planned or unverified.\n\n## Outputs\n\n${outputs}. Link the artifact and evidence on the task card; record open findings and owner.\n\n## Limits\n\n${limits}. Protect student information: use synthetic examples, minimize personal data, and keep credentials and raw feedback out of prompts and artifacts. Do not change GitHub before the exact publication plan is shown to the user.\n\n## Handoff\n\n${handoff}. A head must review each specialist output in its branch. Independent verification, applicable QA, and code review for code changes precede Done.\n\n## Three-pass self-check\n\n1. **Completeness:** Check the assigned scope, current/planned/unverified labels, edge cases, acceptance criteria, outputs, and handoff links.\n2. **Accuracy:** Trace every factual claim to current code, dated tests, or real sourced feedback; mark gaps and stale evidence. Never invent deadlines or quality percentages.\n3. **Security/privacy:** Remove student identifiers, secrets and sensitive uploads; check access, consent, retention, third-party sharing and safe synthetic test data. Record remaining risks.\n`;
 writeFileSync(new URL(`./roles/${slug}.md`,import.meta.url),body);
}
console.log(`Wrote ${roles.length} role files`);
